<#--How do you quantify those commercial objectives?-->


<#--special parameter, 营销场景涉及revenue和treatment cost，以下内容当revenue和treatment cost不为null的时候输出-->

<#assign fairnessInit=jsonModel.fairnessInit>
<#if fairnessInit.special_params.revenue??>

<div>
    The profit generated by the interest on the loan product is ${fairnessInit.special_params.revenue} dollars.
    Each marketing call costs the company ${fairnessInit.special_params.treatment_cost} to execute (including campaign overheads, salaries etc.).
    Only customers who apply for the loan and are accepted are considered to have successfully acquired the product.
    The customers selection process of this system balances profit from lift against rejection rates from lift to maximize benefits.
</div>
</#if>